name: "Linting and Type Checking"
description: "Run linting(ruff) and type-checking(mypy) tools via uv"

inputs:
  python-version:
    description: "The version of Python to use"
    required: true

runs:
  using: "composite"
  
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.8"
        enable-cache: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install the project
      run: uv sync --locked --all-extras --dev
      shell: bash

    - name: Run Ruff format
      run: uv run ruff format --check .
      continue-on-error: true  # Added so to provide lenience while linting
      shell: bash

    - name: Sort imports
      run: uv run ruff check --select I --diff .
      continue-on-error: true  # Added so to provide lenience while linting
      shell: bash

    - name: Run mypy
      run: uv run mypy .
      continue-on-error: true # Added so to provide lenience while linting
      shell: bash
