name: "Linting and Type Checking"
description: "Run linting and type-checking tools like Black, Flake8, isort, and mypy using Poetry"

inputs:
  python-version:
    description: "The version of Python to use"
    required: true

  poetry-version:
    description: "The version of Poetry to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install pipx
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipx
        python -m pipx ensurepath
      shell: bash

    - name: Install Poetry with pipx
      run: pipx install poetry==${{ inputs.poetry-version }}
      shell: bash

    - name: Install dependencies
      run: poetry install
      shell: bash

    - name: Run Black
      run: poetry run black --check .
      shell: bash

    - name: Run Flake8
      run: poetry run flake8 .
      shell: bash

    - name: Run isort
      run: poetry run isort --check .
      shell: bash

    - name: Run mypy
      run: poetry run mypy .
      shell: bash
