name: "Run Test"
description: "Sets up Python environment, installs dependencies using Poetry, and runs tests using pytest"

inputs:
  python-version:
    description: "The version of Python used"
    required: true
  poetry-version:
    description: "The version of Poetry to install"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install pipx
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipx 
        python -m pipx ensurepath
      continue-on-error: true
      shell: bash

    - name: Install Poetry with pipx
      run: pipx install poetry==${{ inputs.poetry-version }}
      continue-on-error: true
      shell: bash

    - name: Update pyproject.toml to fix NumPy path
      run: |
        sed -i 's|numpy = { path = "/artifact/numpy-1.23.3-cp310-cp310-linux_x86_64.whl" }|numpy = "^1.23.3"|' pyproject.toml
        cat pyproject.toml  # Optionally, verify the change
      shell: bash

    - name: Install dependencies
      run: poetry install
      continue-on-error: true
      shell: bash

    - name: Run Test
      run: poetry run pytest
      continue-on-error: true
      shell: bash
