name: "Run Test"
description: "Sets up Python environment, installs dependencies using Poetry, and runs tests using pytest"

inputs:
  python-version:
    description: "The version of Python used"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.8"
        enable-cache: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Update pyproject.toml to fix NumPy path
      run: |
        sed -i 's|numpy = { path = "/artifact/numpy-1.23.3-cp310-cp310-linux_x86_64.whl" }|numpy = "^1.23.3"|' pyproject.toml
        cat pyproject.toml  # Optionally, verify the change
      shell: bash

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Run tests
      run: uv run pytest
      continue-on-error: false
      shell: bash