name: 'Container Image Build and Push to GCR'
description: 'This action authenticates to Google Cloud, builds Docker images, and pushes them to GCR.'

inputs:
  gcr_sa_key:
    description: 'The Google Cloud service account JSON key for authentication.'
    required: true
  lens_dockerfile_path:
    description: 'Path to the Dockerfile for the Lens app.'
    required: true
  superset_dockerfile_path:
    description: 'Path to the Dockerfile for Superset.'
    required: true
  gcr_hostname:
    description: 'The GCR hostname, e.g., gcr.io.'
    required: true
  google_cloud_project:
    description: 'The Google Cloud project ID.'
    required: true
  lens_image_tag:
    description: 'The Docker tag for the Lens image.'
    required: true
  superset_image_tag:
    description: 'The Docker tag for the Superset image.'
    required: true
  github_token:
    description: 'GitHub token for accessing repo-related information (e.g., commit SHA).'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        token_format: "access_token"
        credentials_json: ${{ inputs.gcr_sa_key }}

    - name: Log into Google Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.gcr_hostname }}
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Build and Push Lens app Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ inputs.gcr_hostname }}/${{ inputs.google_cloud_project }}/lens-damage-prevention-test:${{ inputs.lens_image_tag }}
        file: ${{ inputs.lens_dockerfile_path }}
        build-args: |
          PORT=8080
          GITHUB_AUTH_TOKEN=${{ inputs.github_token }}
          APP_COMMIT_SHA=${{ github.sha }}
          APP_COMMIT_URL=${{ github.repository }}/commit/${{ github.sha }}
          APP_BUILD_URL=${{ github.repository }}/actions/runs/${{ github.run_id }}

    - name: Build and Push Superset app Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        context: ${{ inputs.superset_dockerfile_path }}
        tags: ${{ inputs.gcr_hostname }}/${{ inputs.google_cloud_project }}/lens-superset-test:${{ inputs.superset_image_tag }}
