name: "Setup Python Environment"
description: "Sets up Python, installs Poetry, system dependencies, and project dependencies from the current repository"

inputs:
  python-version:
    description: "The version of Python to use"
    required: true
  poetry-version:
    description: "The version of Poetry to install"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout the current repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Upgrade pip and setuptools
      run: |
        python -m pip install --upgrade pip setuptools
      shell: bash

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpq-dev gcc brotli libgeos-dev proj-bin libsnappy-dev python3-dev
        sudo apt-get clean
      shell: bash

    - name: Install Poetry with pip
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry==${{ inputs.poetry-version }}
      shell: bash

    - name: Install dependencies using Poetry (from pyproject.toml)
      run: |
        poetry install
      shell: bash
