name: "Setup Python Environment"
description: "Sets up Python, installs Poetry, system dependencies, and project dependencies"

inputs:
  python-version:
    description: "The version of Python to use"
    required: true
  poetry-version:
    description: "The version of Poetry to install"
    required: true
  repo-path:
    description: "The repository containing pyproject.toml (path or repo name)"
    required: true
  repo-directory:
    description: "The directory where the repository will be checked out"
    required: true
    default: "."
  uvloop-version:
    description: "Version of uvloop to install if necessary"
    required: false
    default: "0.17.0"

runs:
  using: "composite"
  steps:
    - name: Checkout current repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Upgrade pip and setuptools
      run: |
        python -m pip install --upgrade pip setuptools
      shell: bash

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpq-dev gcc brotli libgeos-dev proj-bin libsnappy-dev
        sudo apt-get clean
      shell: bash

    - name: Install pipx
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipx
        python -m pipx ensurepath
      continue-on-error: true
      shell: bash

    - name: Install Poetry with pipx
      run: |
        pipx install poetry==${{ inputs.poetry-version }}
      continue-on-error: true
      shell: bash

    - name: Install dependencies using Poetry (from pyproject.toml)
      run: |
        cd ${{ inputs.repo-directory }}  # Move into the directory where pyproject.toml is
        poetry install
      shell: bash

    - name: Install uvloop manually (if necessary)
      run: |
        pip install --no-cache-dir --use-pep517 uvloop==${{ inputs.uvloop-version }}
      continue-on-error: true
      shell: bash

    - name: Install project dependencies using Poetry (if uvloop was installed manually)
      run: |
        cd ${{ inputs.repo-directory }}  # Move into the directory where pyproject.toml is
        poetry install
      continue-on-error: true
      shell: bash
