name: "Setup Python Environment"
description: "Sets up Python, installs Poetry, and project dependencies"

inputs:
  python-version:
    description: "The version of Python to use"
    required: true
  poetry-version:
    description: "The version of Poetry to install"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install pipx
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipx
        python -m pipx ensurepath
      continue-on-error: true
      shell: bash

    - name: Install Poetry with pipx
      run: pipx install poetry==${{ inputs.poetry-version }}
      continue-on-error: true
      shell: bash

    - name: Install dependencies using Poetry
      run: |
        poetry install
      continue-on-error: true
      shell: bash

    - name: Create and activate virtual environment
      run: |
        poetry shell
      continue-on-error: true
      shell: bash
