name: 'Cloud SQL Backup'
description: 'Takes a backup of a specified Cloud SQL instance based on the environment.'
inputs:
  environment:
    description: 'Environment (integ, staging, prod)'
    required: true
    type: string
    options:
      - integ
      - staging
      - prod
  cloudsql_instance:
    description: 'Name of the Cloud SQL instance to backup'
    required: true
    type: string
  cloudsql_backup_description:
    description: 'Description of the Cloud SQL  backup'
    required: true
    type: string    
runs:
  using: "composite"
  steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ env.CREDENTIALS_JSON }}
        project_id: ${{ env.GCP_PROJECT_ID }}

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}

    - name: 'Use gcloud CLI'
      shell: bash
      run: 'gcloud info'

    - name: Take Cloud SQL Backup
      shell: bash
      run: |
        echo "Creating backup for Cloud SQL instance: ${{ inputs.cloudsql_instance }} in environment: ${{ inputs.environment }}"
        gcloud sql backups create --instance=${{ inputs.cloudsql_instance }} --project=${{ env.GCP_PROJECT_ID }} --description="${{ inputs.cloudsql_backup_description }}"