name: 'Setup PostgreSQL and Redis'
description: 'Set up PostgreSQL and Redis for testing environments'

inputs:
  postgres_version:
    description: 'Version of PostgreSQL to use'
    required: true
    default: 'latest'
  redis_version:
    description: 'Version of Redis to use'
    required: true
    default: 'latest'
  postgres_user:
    description: 'PostgreSQL user'
    required: true
  postgres_password:
    description: 'PostgreSQL password'
    required: true
  postgres_db:
    description: 'PostgreSQL database name'
    required: true
  redis_host:
    description: 'Redis host'
    required: true
    default: 'localhost'
  redis_port:
    description: 'Redis port'
    required: true
    default: '6379'

runs:
  using: 'composite'
  steps:
    - name: Set up PostgreSQL container
      shell: bash
      run: |
        docker run -d \
          --name postgres \
          -e POSTGRES_USER=${{ inputs.postgres_user }} \
          -e POSTGRES_PASSWORD=${{ inputs.postgres_password }} \
          -e POSTGRES_DB=${{ inputs.postgres_db }} \
          -p 5432:5432 \
          postgres:${{ inputs.postgres_version }}
    
    - name: Set up Redis container
      shell: bash
      run: |
        docker run -d \
          --name redis \
          -p 6379:6379 \
          redis:${{ inputs.redis_version }}

    - name: Wait for PostgreSQL to be ready
      shell: bash
      run: |
        until docker exec postgres pg_isready -U ${{ inputs.postgres_user }}; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 2
        done
        echo "PostgreSQL is ready."

    - name: Wait for Redis to be ready
      shell: bash
      run: |
        until docker exec redis redis-cli -h redis ping; do
          echo "Waiting for Redis to be ready..."
          sleep 2
        done
        echo "Redis is ready."
