name: 'Run Migrations'
description: 'Runs migrations for worker safety service'
inputs:
  postgres_host:
    description: 'PostgreSQL host'
    required: true
  postgres_user:
    description: 'PostgreSQL user'
    required: true
  postgres_password:
    description: 'PostgreSQL password'
    required: true
  postgres_db:
    description: 'PostgreSQL database'
    required: true
  migration_image_name:
    description: 'Migration Docker image name'
    required: true
  migration_image_tag:
    description: 'Migration Docker image tag'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run Migration Docker
      
      run: |
        docker run --rm \
          -e POSTGRES_HOST=${{ inputs.postgres_host }} \
          -e POSTGRES_USER=${{ inputs.postgres_user }} \
          -e POSTGRES_PASSWORD=${{ inputs.postgres_password }} \
          -e POSTGRES_DB=${{ inputs.postgres_db }} \
          gcr.io/urbint-1259/${{ inputs.migration_image_name }}:${{ inputs.migration_image_tag }} /bin/bash -c "alembic upgrade head"
      shell: bash  
