name: 'Run Migrations'
description: 'Runs migrations for worker safety service'
inputs:
  postgres_host:
    description: 'PostgreSQL host'
    required: true
  postgres_user:
    description: 'PostgreSQL user'
    required: true
  postgres_password:
    description: 'PostgreSQL password'
    required: true
  postgres_db:
    description: 'PostgreSQL database'
    required: true
  migration_image_name:
    description: 'Migration Docker image name'
    required: true
  migration_image_tag:
    description: 'Migration Docker image tag'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ inputs.gcr_sa_key }}
        token_format: "access_token"  

    - name: Log into Google Container Registry
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Run Migration Docker
      run: |
        docker run --rm \
          -e POSTGRES_HOST=${{ inputs.postgres_host }} \
          -e POSTGRES_USER=${{ inputs.postgres_user }} \
          -e POSTGRES_PASSWORD=${{ inputs.postgres_password }} \
          -e POSTGRES_DB=${{ inputs.postgres_db }} \
          -e GS_BUCKET_NAME=${{ env.GS_BUCKET_NAME }} \
          -v ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}:/tmp/gcp_credentials.json \
          --network=host \
          --entrypoint /bin/bash \
          gcr.io/urbint-1259/${{ inputs.migration_image_name }}:${{ inputs.migration_image_tag }} -c "export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp_credentials.json && alembic upgrade head"
      shell: bash