name: Build and Scan Images
description: Builds and scans Docker images for vulnerabilities
inputs:
  github_token:
    description: 'GitHub Authentication Token'
    required: true
  cindy_pat:
    description: 'Cindy Personal Access Token'
    required: true
  commit_sha:
    description: 'Commit SHA for image tagging'
    required: true
  repository:
    description: 'Repository name'
    required: true
  run_id:
    description: 'GitHub Actions Run ID'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout commit
      uses: actions/checkout@v3

    - name: Build Lens app
      uses: docker/build-push-action@v4
      with:
        push: false
        tags: lens-damage-prevention:${{ inputs.commit_sha }}
        build-args: |
          PORT=8080
          GITHUB_AUTH_TOKEN=${{ inputs.cindy_pat }}
          APP_COMMIT_SHA=${{ inputs.commit_sha }}
          APP_COMMIT_URL=${{ inputs.repository }}/commit/${{ inputs.commit_sha }}
          APP_BUILD_URL=${{ inputs.repository }}/actions/runs/${{ inputs.run_id }}

    - name: Build Superset
      uses: docker/build-push-action@v4
      with:
        push: false
        context: support/docker/superset
        tags: lens-superset:${{ inputs.commit_sha }}

    - name: Cache Trivy DB
      id: cache-trivy-db
      uses: actions/cache@v3
      with:
        path: ~/.cache/trivy
        key: trivy-db-${{ runner.os }}-${{ inputs.commit_sha }}
        restore-keys: |
          trivy-db-${{ runner.os }}-
          trivy-db-

    - name: Install Trivy
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install wget -y
        wget https://github.com/aquasecurity/trivy/releases/download/v0.45.1/trivy_0.45.1_Linux-64bit.deb
        sudo dpkg -i trivy_0.45.1_Linux-64bit.deb

    - name: Update Trivy DB
      shell: bash
      run: |
        trivy db update || echo "Failed to update DB, using cached version."

    - name: Scan Lens Image
      continue-on-error: true
      shell: bash
      run: |
        echo "Scanning Lens Docker image for vulnerabilities..."
        trivy image --exit-code 1 --severity HIGH,CRITICAL lens-damage-prevention:${{ inputs.commit_sha }}

    - name: Scan Superset Image
      continue-on-error: true
      shell: bash
      run: |
        echo "Scanning Superset Docker image for vulnerabilities..."
        trivy image --exit-code 1 --severity HIGH,CRITICAL lens-superset:${{ inputs.commit_sha }}
