name: "Deploy to ArgoCD"
description: "Deploys an application to ArgoCD"

inputs:
  repo:
    description: 'The GitHub repository to check out'
    required: true
  token:
    description: 'GitHub token for authentication'
    required: true
  path:
    description: 'Path to the repository after checkout'
    required: true
  ref:
    description: 'Reference (branch/tag) to checkout'
    required: true
  argocd_server:
    description: 'ArgoCD server URL'
    required: true
  argocd_token:
    description: 'ArgoCD authentication token'
    required: true
  app_name:
    description: 'Name of the ArgoCD application to sync'
    required: true

runs:
  using: "composite"
  steps:
    # Step 1: Checkout GitOps repository
    - name: Checkout GitOps Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        token: ${{ inputs.token }}
        path: ${{ inputs.path }}
        ref: ${{ inputs.ref }}

    # Step 2: Install ArgoCD CLI
    - name: Install ArgoCD CLI
      run: |
        echo "Installing ArgoCD CLI..."
        curl -sSL https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 -o argocd
        chmod +x argocd
        sudo mv argocd /usr/local/bin/
        argocd version
      shell: bash

    # Step 3: Debugging Step - Print environment variables and check ArgoCD CLI status
    - name: Check environment and argocd version
      run: |
        echo "ArgoCD Server: ${{ inputs.argocd_server }}"
        echo "ArgoCD Token: ${{ inputs.argocd_token }}"  # Sensitive data, avoid printing in production
        echo "Checking ArgoCD CLI version..."
        argocd version
        echo "Listing ArgoCD CLI configuration..."
        argocd context
      shell: bash

    # Step 4: Log in to ArgoCD using Auth Token
    - name: Log in to ArgoCD
      run: |
        echo "Logging in to ArgoCD using the provided auth token..."
        argocd login ${{ inputs.argocd_server }} --server ${{ inputs.argocd_server }} --auth-token ${{ inputs.argocd_token }} --insecure --grpc-web
        echo "Successfully logged into ArgoCD."
      shell: bash
