name: 'Setup Terraform and Google Cloud'
description: 'Setup Terraform and Google Cloud SDK for the workflow'

inputs:
  gcp_key:
    description: 'Base64 encoded Google Cloud service account key'
    required: true
  gcp_project:
    description: 'Google Cloud project ID'
    required: true
  terraform_version:
    description: 'Terraform version to install'
    default: '1.5.0'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Decode and Set up Google Cloud credentials
      shell: bash
      run: |
        echo ${{ inputs.gcp_key }} | base64 --decode > $GITHUB_WORKSPACE/gcp-key.json
        gcloud auth activate-service-account --key-file=$GITHUB_WORKSPACE/gcp-key.json
        gcloud config set project ${{ inputs.gcp_project }}
